### ISSUE TITLE
Магические константы в классе TleParser

### ISSUE THREAD

**Issue by puchninanastya** [BorodinDmitriy/SpaceTracker#6]
В методах класса используются магические значения.
`for (int i = 64; i < 68; i++) 
{ 
buf += str[i]; 
}` 
На мой взгляд, желательно вынести эти значения в отдельный файл константы начала и константы конца с указанием наименования поля для самодокументированности кода.

**Comment by BorodinDmitriy** [comment]
Поправлено в pull-request #7
